set(CMAKE_INFO_SH ${CMAKE_CURRENT_SOURCE_DIR}/../libict-dev-tools/info.sh)
add_custom_command(
  OUTPUT ${CMAKE_CURRENT_SOURCE_DIR}/info.hpp 
  COMMAND ${CMAKE_INFO_SH} ${LIBRARY_NAME} info.hpp
  DEPENDS ${CMAKE_INFO_SH}
  WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
)
add_custom_command(
  OUTPUT ${CMAKE_CURRENT_SOURCE_DIR}/info.cpp 
  COMMAND ${CMAKE_INFO_SH} ${LIBRARY_NAME} info.cpp
  DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/info.hpp ${CMAKE_CURRENT_SOURCE_DIR}/../LICENSE
  WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
)