set(CMAKE_TEST_SH ${CMAKE_CURRENT_SOURCE_DIR}/../libict-dev-tools/test.sh)
add_custom_command(
  OUTPUT ${CMAKE_CURRENT_SOURCE_DIR}/test.hpp 
  COMMAND ${CMAKE_TEST_SH} test.hpp
  DEPENDS ${CMAKE_TEST_SH}
  WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
)
add_custom_command(
  OUTPUT ${CMAKE_CURRENT_SOURCE_DIR}/test.cpp 
  COMMAND ${CMAKE_TEST_SH} test.cpp
  DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/test.hpp
  WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
)